PROC LOGISTIC DATA = CVD DESCENDING;
MODEL CVD = SMOKING_LEVEL;
RUN;

PROC GENMOD DATA = CVD DESCENDING;
MODEL CVD = SMOKING_LEVEL / DIST = BIN LINK = LOGIT;
RUN;

/*使用Dummy variable*/
PROC GENMOD DATA = CVD DESCENDING;
CLASS SMOKING_LEVEL(REF = '0') / PARAM = REF;
MODEL CVD = SMOKING_LEVEL / DIST = BIN LINK = LOGIT;
RUN;

/*看抽菸跟性別有無交互作用*/
PROC GENMOD DATA = CVD DESCENDING;
CLASS SMOKING_LEVEL(REF = '0') / PARAM = REF;
MODEL CVD = SMOKING_LEVEL GENDER SMOKING_LEVEL * GENDER / DIST = BIN LINK = LOGIT;
RUN;
